# Generated by Django 5.2 on 2025-05-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='freelancer_images/'),
        ),
    ]
