# Generated by Django 5.2 on 2025-05-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_workimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
