# Generated by Django 5.2 on 2025-05-04 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_freelancer_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='app.freelancer'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='app.freelancer'),
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='profile_picture',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
