# Generated by Django 5.2 on 2025-05-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
